export {default as Navbar} from './Navbar/Navbar'
export {default as MeioContato} from './MeioContato/MeioContato'
export {default as SoftSkill} from './SoftSkill/SoftSkill'
export {default as HardSkill} from './HardSkill/HardSkill'
export {default as Project} from './Project/Project'